### PR TITLE
Added German Translation

### PR DESCRIPTION
**Pull request by jonas2515**
Kodi for german users.
Could somebody send a screenshot of the list which includes this string:
<string name="cast_list_text">%1$s und %2$s</string>

It's hard to translate "as", if you don't know the context.

### CODE REVIEW

**Comment by SyncedSynapse** [comment]
Thank you very much.

%1$s und %2$s is used in the cast list (eg: Sean Connery as James Bond).

**Comment by jonas2515** [comment]
Ok thank you, now it can be merged.

**Comment by SyncedSynapse** [comment]
How would you like to be credited in the credits (name/alias/whatever)?

**Comment by jonas2515** [comment]
Use my alias, thank you.
I just fixed some typos, I'll make a new pull request. Now it should be perfect.

**Pull request merged**
